language: node_js
node_js:
  - "8"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  repo: logolang/logolang.github.io
  target_branch: master
  github_token: $GITHUB_PAGES_DEPLOY_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master